/** Table id → {rarity, type}, générée depuis src/data/cards.json par
 *  scripts/gen-card-meta.mjs — ne pas éditer à la main. Les Pages
 *  Functions n'importent pas le catalogue front-end (voir SECRET_CARD_ID
 *  dans functions/api/profile/[username].ts) — même logique ici, à
 *  l'échelle de tout le catalogue : la puissance de combat dépend de la
 *  rareté (functions/_lib/battle.ts), calculée côté serveur — jamais fait
 *  confiance à ce que le client prétend, donc il lui faut sa propre
 *  source de vérité. Relancer ce script après tout ajout/retrait de
 *  carte ou changement de rareté/catégorie dans cards.json. */

export interface CardMeta {
  rarity: number;
  type: string;
}

export const CARD_META: Record<number, CardMeta> = {
  1: { rarity: 1, type: "Métiers" },
  2: { rarity: 1, type: "Métiers" },
  3: { rarity: 1, type: "Métiers" },
  4: { rarity: 4, type: "Politiques" },
  5: { rarity: 2, type: "Religion" },
  6: { rarity: 3, type: "Simpson" },
  7: { rarity: 3, type: "Célébrités" },
  8: { rarity: 3, type: "Humains" },
  9: { rarity: 1, type: "Métiers" },
  10: { rarity: 2, type: "Art" },
  11: { rarity: 2, type: "Film" },
  12: { rarity: 3, type: "Dictateurs" },
  13: { rarity: 1, type: "Hors catégorie" },
  14: { rarity: 2, type: "Humains" },
  15: { rarity: 1, type: "Hors catégorie" },
  16: { rarity: 1, type: "Humains" },
  17: { rarity: 2, type: "Humains" },
  18: { rarity: 3, type: "Humains" },
  19: { rarity: 5, type: "Film" },
  20: { rarity: 3, type: "Humains" },
  21: { rarity: 4, type: "Hors catégorie" },
  22: { rarity: 3, type: "Eléments chimique" },
  23: { rarity: 2, type: "Hors catégorie" },
  24: { rarity: 2, type: "Eléments chimique" },
  25: { rarity: 2, type: "Eléments chimique" },
  26: { rarity: 3, type: "Eléments chimique" },
  27: { rarity: 2, type: "Eléments chimique" },
  28: { rarity: 4, type: "Eléments chimique" },
  29: { rarity: 4, type: "Eléments chimique" },
  30: { rarity: 3, type: "Humains" },
  31: { rarity: 2, type: "Eléments chimique" },
  32: { rarity: 6, type: "Hors catégorie" },
  33: { rarity: 1, type: "Célébrités" },
  34: { rarity: 1, type: "Hors catégorie" },
  35: { rarity: 2, type: "Hors catégorie" },
  36: { rarity: 3, type: "Hors catégorie" },
  37: { rarity: 2, type: "Politiques" },
  38: { rarity: 4, type: "Hors catégorie" },
  39: { rarity: 2, type: "Film" },
  40: { rarity: 5, type: "Humains" },
  41: { rarity: 1, type: "Humains" },
  42: { rarity: 3, type: "Meme" },
  43: { rarity: 3, type: "Hors catégorie" },
  44: { rarity: 1, type: "Humains" },
  45: { rarity: 2, type: "Humains" },
  46: { rarity: 4, type: "Humains" },
  47: { rarity: 2, type: "Meme" },
  48: { rarity: 1, type: "Hors catégorie" },
  49: { rarity: 4, type: "Hors catégorie" },
  50: { rarity: 4, type: "Politiques" },
  51: { rarity: 1, type: "Politiques" },
  52: { rarity: 1, type: "Humains" },
  53: { rarity: 5, type: "Série" },
  54: { rarity: 1, type: "Film" },
  55: { rarity: 3, type: "Hors catégorie" },
  56: { rarity: 2, type: "Hors catégorie" },
  57: { rarity: 1, type: "Hors catégorie" },
  58: { rarity: 3, type: "Hors catégorie" },
  59: { rarity: 5, type: "Dictateurs" },
  60: { rarity: 5, type: "Hors catégorie" },
  61: { rarity: 2, type: "Série" },
  62: { rarity: 3, type: "Hors catégorie" },
  63: { rarity: 4, type: "Super-héros" },
  64: { rarity: 2, type: "Film" },
  65: { rarity: 2, type: "Hors catégorie" },
  66: { rarity: 2, type: "Graille" },
  67: { rarity: 4, type: "Humains" },
  68: { rarity: 3, type: "Humains" },
  69: { rarity: 2, type: "Hors catégorie" },
  70: { rarity: 3, type: "Super-héros" },
  71: { rarity: 5, type: "Religion" },
  72: { rarity: 1, type: "Pokemon" },
  73: { rarity: 2, type: "Film" },
  74: { rarity: 1, type: "Humains" },
  75: { rarity: 1, type: "Humains" },
  76: { rarity: 2, type: "Humains" },
  77: { rarity: 3, type: "Humains" },
  78: { rarity: 3, type: "Religion" },
  79: { rarity: 5, type: "Hors catégorie" },
  80: { rarity: 3, type: "Film" },
  81: { rarity: 2, type: "Hors catégorie" },
  82: { rarity: 3, type: "Sapeurs" },
  83: { rarity: 2, type: "Politiques" },
  84: { rarity: 1, type: "Hors catégorie" },
  85: { rarity: 2, type: "Dictateurs" },
  86: { rarity: 1, type: "Hors catégorie" },
  87: { rarity: 1, type: "Hors catégorie" },
  88: { rarity: 1, type: "Graille" },
  89: { rarity: 1, type: "Hors catégorie" },
  90: { rarity: 3, type: "Simpson" },
  91: { rarity: 4, type: "Simpson" },
  92: { rarity: 3, type: "Dragon Ball" },
  93: { rarity: 2, type: "Hors catégorie" },
  94: { rarity: 3, type: "Hors catégorie" },
  95: { rarity: 1, type: "Hors catégorie" },
  96: { rarity: 3, type: "Hors catégorie" },
  97: { rarity: 4, type: "Hors catégorie" },
  98: { rarity: 3, type: "Hors catégorie" },
  99: { rarity: 1, type: "Hors catégorie" },
  100: { rarity: 5, type: "Hors catégorie" },
  101: { rarity: 3, type: "Hors catégorie" },
  102: { rarity: 2, type: "Hors catégorie" },
  103: { rarity: 5, type: "Pokemon" },
  104: { rarity: 2, type: "Hors catégorie" },
  105: { rarity: 1, type: "Hors catégorie" },
  106: { rarity: 1, type: "Dictateurs" },
  107: { rarity: 1, type: "Hors catégorie" },
  108: { rarity: 3, type: "Dictateurs" },
  109: { rarity: 4, type: "Graille" },
  110: { rarity: 5, type: "Super-héros" },
  111: { rarity: 2, type: "Simpson" },
  112: { rarity: 1, type: "Simpson" },
  113: { rarity: 2, type: "Film" },
  114: { rarity: 1, type: "Film" },
  115: { rarity: 3, type: "Célébrités" },
  116: { rarity: 5, type: "Célébrités" },
  117: { rarity: 4, type: "Dictateurs" },
  118: { rarity: 1, type: "Dragon Ball" },
  119: { rarity: 5, type: "Dragon Ball" },
  120: { rarity: 3, type: "Politiques" },
  121: { rarity: 3, type: "Film" },
  122: { rarity: 4, type: "Film" },
  123: { rarity: 1, type: "Célébrités" },
  124: { rarity: 1, type: "Hors catégorie" },
  125: { rarity: 1, type: "Dictateurs" },
  126: { rarity: 2, type: "Super-héros" },
  127: { rarity: 1, type: "Hors catégorie" },
  128: { rarity: 2, type: "Sapeurs" },
  129: { rarity: 1, type: "Sapeurs" },
  130: { rarity: 5, type: "Sapeurs" },
  131: { rarity: 2, type: "Hors catégorie" },
  132: { rarity: 1, type: "Hors catégorie" },
  133: { rarity: 2, type: "Hors catégorie" },
  134: { rarity: 1, type: "Humains" },
  135: { rarity: 2, type: "Humains" },
  136: { rarity: 1, type: "Humains" },
  137: { rarity: 1, type: "Célébrités" },
  138: { rarity: 5, type: "Graille" },
  139: { rarity: 3, type: "Humains" },
  140: { rarity: 2, type: "Jeux-vidéo" },
  141: { rarity: 4, type: "Jeux-vidéo" },
  142: { rarity: 3, type: "Film" },
  143: { rarity: 1, type: "Hors catégorie" },
  144: { rarity: 2, type: "Pokemon" },
  145: { rarity: 3, type: "Hors catégorie" },
  146: { rarity: 5, type: "Jeux-vidéo" },
  147: { rarity: 3, type: "Pokemon" },
  148: { rarity: 4, type: "Film" },
  149: { rarity: 1, type: "Hors catégorie" },
  150: { rarity: 3, type: "Super-héros" },
  151: { rarity: 2, type: "Simpson" },
  152: { rarity: 4, type: "BD" },
  153: { rarity: 4, type: "BD" },
  154: { rarity: 1, type: "Humains" },
  155: { rarity: 1, type: "Mangas" },
  156: { rarity: 1, type: "Jeux-vidéo" },
  157: { rarity: 2, type: "Dragon Ball" },
  158: { rarity: 3, type: "Jeux-vidéo" },
  159: { rarity: 1, type: "Mythologie" },
  160: { rarity: 3, type: "Mythologie" },
  161: { rarity: 2, type: "Mythologie" },
  162: { rarity: 4, type: "Mythologie" },
  163: { rarity: 5, type: "Mythologie" },
  164: { rarity: 1, type: "Mythologie" },
  165: { rarity: 2, type: "Mythologie" },
  166: { rarity: 1, type: "Humains" },
  167: { rarity: 4, type: " Mangas" },
  168: { rarity: 2, type: "Politiques" },
  169: { rarity: 1, type: "Hors catégorie" },
  170: { rarity: 3, type: " Mangas" },
  171: { rarity: 1, type: "Hors catégorie" },
  172: { rarity: 4, type: "Mangas" },
  173: { rarity: 1, type: "Mangas" },
  174: { rarity: 1, type: "Art" },
  175: { rarity: 4, type: "Art" },
  176: { rarity: 2, type: "Art" },
  177: { rarity: 4, type: "Art" },
  178: { rarity: 5, type: "Art" },
  179: { rarity: 1, type: "Art" },
  180: { rarity: 2, type: "Dictateurs" },
  181: { rarity: 1, type: "Film" },
  182: { rarity: 4, type: "Hors catégorie" },
  183: { rarity: 4, type: "Art" },
  184: { rarity: 7, type: "Mystère" },
  185: { rarity: 1, type: "Meme" },
  186: { rarity: 2, type: "Harry Potter" },
  187: { rarity: 4, type: "LOTR" },
  188: { rarity: 4, type: "Harry Potter" },
  189: { rarity: 1, type: "Hors catégorie" },
  190: { rarity: 5, type: "YuGiOh" },
  191: { rarity: 1, type: "Film" },
  192: { rarity: 5, type: "Hors catégorie" },
  193: { rarity: 2, type: "Harry Potter" },
  194: { rarity: 3, type: "Film" },
  195: { rarity: 2, type: "Graille" },
  196: { rarity: 2, type: "Harry Potter" },
  197: { rarity: 1, type: "Humains" },
  198: { rarity: 4, type: "LOTR" },
  199: { rarity: 3, type: "Célébrités" },
  200: { rarity: 1, type: "Hors catégorie" },
  201: { rarity: 1, type: "Jeux-vidéo" },
  202: { rarity: 2, type: "Hors catégorie" },
  203: { rarity: 3, type: "Pokemon" },
  204: { rarity: 4, type: "YuGiOh" },
  205: { rarity: 1, type: "Jeux-vidéo" },
  206: { rarity: 2, type: "YuGiOh" },
  207: { rarity: 1, type: "Humains" },
  208: { rarity: 2, type: "YuGiOh" },
  209: { rarity: 4, type: "Jeux-vidéo" },
  210: { rarity: 1, type: "Hors catégorie" },
  211: { rarity: 1, type: "Graille" },
  212: { rarity: 4, type: "Film" },
  213: { rarity: 2, type: "Film" },
  214: { rarity: 1, type: "Jeux-vidéo" },
  215: { rarity: 2, type: "Harry Potter" },
  216: { rarity: 3, type: "Hors catégorie" },
  217: { rarity: 1, type: "Métiers" },
  218: { rarity: 1, type: "Humains" },
  219: { rarity: 2, type: "Hors catégorie" },
  220: { rarity: 1, type: "Fantastique" },
  221: { rarity: 2, type: "Fantastique" },
  222: { rarity: 1, type: "Hors catégorie" },
  223: { rarity: 1, type: "Dinosaures" },
  224: { rarity: 2, type: "Fruits" },
  225: { rarity: 4, type: "Métiers" },
  226: { rarity: 1, type: "Dinosaures" },
  227: { rarity: 2, type: "Dinosaures" },
  228: { rarity: 2, type: "Fruits" },
  229: { rarity: 3, type: "Humains" },
  230: { rarity: 3, type: "Humains" },
  231: { rarity: 2, type: "Fruits" },
  232: { rarity: 1, type: "One Piece" },
  233: { rarity: 3, type: "One Piece" },
  234: { rarity: 2, type: "One Piece" },
  235: { rarity: 2, type: "One Piece" },
  236: { rarity: 3, type: "Jeux-vidéo" },
  237: { rarity: 2, type: "Série" },
  238: { rarity: 4, type: "Série" },
  239: { rarity: 3, type: "Série" },
  240: { rarity: 4, type: "One Piece" },
  241: { rarity: 5, type: "One Piece" },
  242: { rarity: 2, type: "One Piece" },
  243: { rarity: 1, type: "Graille" },
  244: { rarity: 2, type: "Meme" },
  245: { rarity: 4, type: "Meme" },
  246: { rarity: 6, type: "Meme" },
  247: { rarity: 4, type: "Série" },
  248: { rarity: 3, type: "Série" },
  249: { rarity: 3, type: "Série" },
  250: { rarity: 1, type: "Star Wars" },
  251: { rarity: 5, type: "Star Wars" },
  252: { rarity: 4, type: "Hors catégorie" },
  253: { rarity: 4, type: "Super-héros" },
  254: { rarity: 5, type: "Star Wars" },
  255: { rarity: 2, type: "Star Wars" },
  256: { rarity: 4, type: "Star Wars" },
  257: { rarity: 1, type: "Métiers" },
  258: { rarity: 1, type: "BD" },
  259: { rarity: 2, type: "Humains" },
  260: { rarity: 1, type: "Star Wars" },
  261: { rarity: 5, type: "Jeux-vidéo" },
  262: { rarity: 4, type: "YuGiOh" },
  263: { rarity: 2, type: "Humains" },
  264: { rarity: 3, type: "YuGiOh" },
  265: { rarity: 2, type: "Jeux-vidéo" },
  266: { rarity: 3, type: "Jeux-vidéo" },
  267: { rarity: 3, type: "Jeux-vidéo" },
  268: { rarity: 5, type: "YuGiOh" },
  269: { rarity: 3, type: "Star Wars" },
  270: { rarity: 2, type: "Star Wars" },
  271: { rarity: 1, type: "Star Wars" },
  272: { rarity: 1, type: "Célébrités" },
  273: { rarity: 4, type: "YuGiOh" },
  274: { rarity: 4, type: "Star Wars" },
  275: { rarity: 2, type: "Célébrités" },
  276: { rarity: 3, type: "Harry Potter" },
};
